2024-09-25 16:05:13.%f +0530 monitor - INFO - Started
2024-09-25 22:31:01.%f +0530 monitor - INFO - Started
2024-09-25 22:31:07.%f +0530 monitor - CRITICAL - Exiting because of exception: HTTPSConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /input (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))
2024-09-25 22:31:07.%f +0530 monitor - CRITICAL - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/usr/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sridhar/hackathon/engine/main.py", line 223, in main
    setup_minio_buckets()
  File "/home/sridhar/hackathon/engine/main.py", line 43, in setup_minio_buckets
    found = minio_client.bucket_exists("input")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sridhar/.local/lib/python3.12/site-packages/minio/api.py", line 696, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/sridhar/.local/lib/python3.12/site-packages/minio/api.py", line 440, in _execute
    return self._url_open(
           ^^^^^^^^^^^^^^^
  File "/home/sridhar/.local/lib/python3.12/site-packages/minio/api.py", line 302, in _url_open
    response = self._http.urlopen(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /input (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)')))

2024-09-25 22:35:27.%f +0530 monitor - INFO - Started
2024-09-25 22:35:27.%f +0530 monitor - CRITICAL - Exiting because of exception: S3 operation failed; code: AccessDenied, message: Access denied, resource: /input, request_id: 17F88B949073C5B2, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: input
2024-09-25 22:35:27.%f +0530 monitor - CRITICAL - Traceback (most recent call last):
  File "/home/sridhar/hackathon/engine/main.py", line 223, in main
    setup_minio_buckets()
  File "/home/sridhar/hackathon/engine/main.py", line 43, in setup_minio_buckets
    found = minio_client.bucket_exists("input")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sridhar/.local/lib/python3.12/site-packages/minio/api.py", line 696, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/sridhar/.local/lib/python3.12/site-packages/minio/api.py", line 440, in _execute
    return self._url_open(
           ^^^^^^^^^^^^^^^
  File "/home/sridhar/.local/lib/python3.12/site-packages/minio/api.py", line 423, in _url_open
    raise response_error
minio.error.S3Error: S3 operation failed; code: AccessDenied, message: Access denied, resource: /input, request_id: 17F88B949073C5B2, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: input

2024-09-25 22:38:40.%f +0530 monitor - INFO - Started
2024-09-25 22:39:35.%f +0530 monitor - INFO - Started
2024-09-25 22:50:00.%f +0530 monitor - INFO - Started
2024-09-27 08:27:58.%f +0530 monitor - INFO - Started
2024-09-27 08:27:58.%f +0530 monitor - INFO - Started
2024-09-27 08:28:15.%f +0530 monitor - INFO - Started
2024-09-27 08:28:15.%f +0530 monitor - INFO - Started
2024-09-27 08:33:32.%f +0530 monitor - INFO - Started
2024-09-27 08:33:32.%f +0530 monitor - INFO - Started
2024-09-27 08:35:14.%f +0530 monitor - INFO - Started
2024-09-27 08:35:14.%f +0530 monitor - INFO - Started
2024-09-27 08:43:21.%f +0530 monitor - INFO - Started
2024-09-27 08:43:21.%f +0530 monitor - INFO - Started
2024-09-27 08:48:09.%f +0530 monitor - INFO - Started
2024-09-27 08:48:09.%f +0530 monitor - INFO - Started
2024-09-27 08:58:04.%f +0530 monitor - INFO - Started
2024-09-27 08:58:04.%f +0530 monitor - INFO - Started
2024-09-27 09:16:20.%f +0530 monitor - INFO - Started
2024-09-27 09:16:20.%f +0530 monitor - INFO - Started
2024-09-27 09:18:52.%f +0530 monitor - INFO - Started
2024-09-27 09:18:52.%f +0530 monitor - INFO - Started
